name: SolarRanks
version: 1.0
main: com.solarcraftmc.ranks.Ranks
author: Spy
description: Ranking Plugin for SolarCraft Prisons

commands:
		ranks:
			usage: /<command>
			description: Rank list command!
